packages:
    - 'ts-base'
    - 'ts-ui'
    - 'ts-views'
    - 'ts-views/**'
    - 'study/types'
    - 'study/cli'
    - 'study-core'
    - '!study'
    - 'study-sync'
    - 'ts-config/*'

onlyBuiltDependencies:
    - electron
    - esbuild
    - sqlite3
