/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseIdTaskTaskIdRouteImport } from './routes/course.$courseId.task.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdTaskTaskIdRoute =
  CourseCourseIdTaskTaskIdRouteImport.update({
    id: '/course/$courseId/task/$taskId',
    path: '/course/$courseId/task/$taskId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course/$courseId/task/$taskId': typeof CourseCourseIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course/$courseId/task/$taskId': typeof CourseCourseIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course/$courseId/task/$taskId': typeof CourseCourseIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/course/$courseId/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/course/$courseId/task/$taskId'
  id: '__root__' | '/' | '/course/$courseId/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseCourseIdTaskTaskIdRoute: typeof CourseCourseIdTaskTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/task/$taskId': {
      id: '/course/$courseId/task/$taskId'
      path: '/course/$courseId/task/$taskId'
      fullPath: '/course/$courseId/task/$taskId'
      preLoaderRoute: typeof CourseCourseIdTaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseCourseIdTaskTaskIdRoute: CourseCourseIdTaskTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
